import type { LucideIcon } from "lucide-react";
import {
  CalendarDays, ClipboardPlus, Stethoscope, BedDouble, Siren, Scissors,
  Shield, TestTube, FlaskConical, Droplets, Scan, Boxes, BarChart3,
  HeartPulse, Settings2, FileCheck2, FilePenLine, Wrench, UserPlus,
  Pill, Receipt, LogOut, MessageSquare, Activity, Hospital,
} from "lucide-react";

export interface DashboardModule {
  id: string;
  label: string;
  icon: LucideIcon;
  color: string;
  href: string;
  journeyStep?: number;
  blurb: string;
}

/** HIS module tiles — styled like the reference dashboard, mapped to our patient journey. */
export const DASHBOARD_MODULES: DashboardModule[] = [
  {
    id: "registration",
    label: "Patient Registration",
    icon: UserPlus,
    color: "#1B6EC2",
    href: "/product/patient-access",
    journeyStep: 1,
    blurb: "Register patients, capture ID/ABHA, and open the chart.",
  },
  {
    id: "appointment",
    label: "Appointment",
    icon: CalendarDays,
    color: "#0E8388",
    href: "/product/appointments",
    journeyStep: 2,
    blurb: "Book slots, manage queues, and cut no-shows.",
  },
  {
    id: "clinical",
    label: "Clinical / OPD",
    icon: Stethoscope,
    color: "#5BB4A6",
    href: "/product/emr",
    journeyStep: 3,
    blurb: "Doctor consultation, EMR notes, and orders.",
  },
  {
    id: "lab",
    label: "Laboratory",
    icon: FlaskConical,
    color: "#E0912F",
    href: "/product/lab",
    journeyStep: 4,
    blurb: "Lab orders, analyzers, and validated results.",
  },
  {
    id: "radiology",
    label: "Radiology",
    icon: Scan,
    color: "#1B6EC2",
    href: "/product/radiology",
    journeyStep: 4,
    blurb: "RIS, DICOM viewer, and structured reports.",
  },
  {
    id: "pharmacy",
    label: "Pharmacy",
    icon: Pill,
    color: "#1E9E63",
    href: "/product/pharmacy",
    journeyStep: 5,
    blurb: "e-Prescribe, dispense, and eMAR closed-loop.",
  },
  {
    id: "daycare",
    label: "Day Care",
    icon: BedDouble,
    color: "#0A6B70",
    href: "/product/clinical",
    journeyStep: 6,
    blurb: "Day-care admission and observation workflows.",
  },
  {
    id: "ipd",
    label: "Admission (IPD)",
    icon: Hospital,
    color: "#10303B",
    href: "/product/clinical",
    journeyStep: 6,
    blurb: "IPD bed board, transfers, and ward care.",
  },
  {
    id: "er",
    label: "Emergency Room",
    icon: Siren,
    color: "#D64545",
    href: "/product/clinical",
    journeyStep: 7,
    blurb: "Triage, ER board, and critical pathways.",
  },
  {
    id: "ot",
    label: "Operation Theatre",
    icon: Scissors,
    color: "#C0362C",
    href: "/product/clinical",
    journeyStep: 7,
    blurb: "OT scheduling, checklists, and notes.",
  },
  {
    id: "icu",
    label: "ICU / Critical Care",
    icon: Activity,
    color: "#D64545",
    href: "/product/clinical",
    journeyStep: 7,
    blurb: "ICU flowsheets, monitors, and rounds.",
  },
  {
    id: "billing",
    label: "Billing & Invoices",
    icon: Receipt,
    color: "#0E8388",
    href: "/product/billing-invoices",
    journeyStep: 8,
    blurb: "Patient bills, GST invoices, and payments.",
  },
  {
    id: "insurance",
    label: "Insurance & eClaim",
    icon: Shield,
    color: "#1B6EC2",
    href: "/product/revenue-cycle",
    journeyStep: 8,
    blurb: "Eligibility, claims, and denial queues.",
  },
  {
    id: "discharge",
    label: "Discharge Summary",
    icon: FileCheck2,
    color: "#1E9E63",
    href: "/product/emr",
    journeyStep: 9,
    blurb: "AI-assisted discharge and final settlement.",
  },
  {
    id: "reminders",
    label: "Follow-up & Reminders",
    icon: MessageSquare,
    color: "#5BB4A6",
    href: "/product/patient-reminders",
    journeyStep: 10,
    blurb: "SMS/WhatsApp reminders and patient portal.",
  },
  {
    id: "nurse",
    label: "Nurse Station",
    icon: HeartPulse,
    color: "#0E8388",
    href: "/product/clinical",
    blurb: "eMAR, vitals, and nursing worklists.",
  },
  {
    id: "phlebotomy",
    label: "Phlebotomy",
    icon: TestTube,
    color: "#E0912F",
    href: "/product/lab",
    blurb: "Sample collection and barcode tracking.",
  },
  {
    id: "bloodbank",
    label: "Blood Bank",
    icon: Droplets,
    color: "#C0362C",
    href: "/product/lab",
    blurb: "Units, cross-match, and issue logs.",
  },
  {
    id: "inventory",
    label: "Inventory",
    icon: Boxes,
    color: "#10303B",
    href: "/product/supply-chain",
    blurb: "Stock, FEFO batches, and reorder.",
  },
  {
    id: "mis",
    label: "MIS Reports",
    icon: BarChart3,
    color: "#1B6EC2",
    href: "/product/analytics",
    blurb: "Operational and financial dashboards.",
  },
  {
    id: "templates",
    label: "Custom Template",
    icon: FilePenLine,
    color: "#5BB4A6",
    href: "/product/platform",
    blurb: "Form Builder clinical templates.",
  },
  {
    id: "admin",
    label: "Software Management",
    icon: Wrench,
    color: "#0A6B70",
    href: "/product/platform",
    blurb: "Roles, workflows, and white-label.",
  },
  {
    id: "setup",
    label: "Inventory Setup",
    icon: Settings2,
    color: "#3A4A50",
    href: "/product/supply-chain",
    blurb: "Masters, stores, and procurement rules.",
  },
  {
    id: "clipboard",
    label: "Clinical Management",
    icon: ClipboardPlus,
    color: "#0E8388",
    href: "/product/clinical",
    blurb: "Orders, care plans, and chart overview.",
  },
];

export const PATIENT_JOURNEY = [
  { step: 1, title: "Patient Registration", flow: "Create / find patient, capture demographics & ABHA", moduleId: "registration" },
  { step: 2, title: "Appointment Booking", flow: "Schedule OPD / teleconsult with live slots", moduleId: "appointment" },
  { step: 3, title: "Doctor Consultation (OPD)", flow: "EMR note, diagnosis, and orders", moduleId: "clinical" },
  { step: 4, title: "Lab / Radiology Orders", flow: "Diagnostics ordered from the chart", moduleId: "lab" },
  { step: 5, title: "Pharmacy", flow: "Prescribe, dispense, and counsel", moduleId: "pharmacy" },
  { step: 6, title: "Admission (IPD if required)", flow: "Bed allocation and inpatient chart", moduleId: "ipd" },
  { step: 7, title: "OT / ICU / Emergency", flow: "Specialized care when needed", moduleId: "ot" },
  { step: 8, title: "Billing & Insurance", flow: "Invoices, payments, and claims", moduleId: "billing" },
  { step: 9, title: "Discharge", flow: "Summary, medicines, and settlement", moduleId: "discharge" },
  { step: 10, title: "Follow-up & Patient Portal", flow: "Reminders, portal access, recalls", moduleId: "reminders" },
] as const;

export const DASHBOARD_SIDEBAR = [
  { id: "home", icon: Hospital, label: "Home" },
  { id: "patients", icon: UserPlus, label: "Patients" },
  { id: "appointments", icon: CalendarDays, label: "Appointments" },
  { id: "clinical", icon: Stethoscope, label: "Clinical" },
  { id: "billing", icon: Receipt, label: "Billing" },
  { id: "reports", icon: BarChart3, label: "Reports" },
  { id: "settings", icon: Settings2, label: "Settings" },
  { id: "logout", icon: LogOut, label: "Exit" },
];
